# Tam thoi: dong goi build/ da build san tren host vao nginx (tranh OOM khi build CRA trong Docker).
FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
